name: experiment
optimize: False         # Turns optimizer mode on and off
seq: False              # Turns sequential mode on and off
plot: ['only']            # Plot modes to activate: single, seq, only
conf: src/config.yaml
confSeq: src/configSeq.yaml
confPlot: plotConfig.yaml
outputDir: src/output
debug: False
successString: ' - finished'
optimizer:
  numTrials: 2
  numJobs: 1