name: test run
optimize: False     # Turns optimizer mode on and off
seq: False         # Turns sequential mode on and off
plot: True

conf: src/config.yaml
confSeq: src/configSeq.yaml
outputDir: src/output
debug: False
optimizer:
  numTrials: 2
  numJobs: 1
plotParams:
  x: [iteration, iteration]
  ys: [['globalClusteringCoef'], ['density']]
  # higherDir: 'lab 3\knn without threshold notBalanced'        # [ONLY FOR HIGHER PLOTS] In addition to output
  yLabels: ['chebyshev', 'euclidean', 'manhattan']    # fixme - careful with the order of directories
successString: ' - finished'
