dataset: 'src/data/power.gml'
attackType: hubs  # random, hubs, clusters, betweenness
stopCondition: lostPercentage # density, clusters, lostPercentage
stopCondArgs:
  threshold: 0.3  # density: 53e-5, clusters: original = 0.103, lostPercentage:
hubPercentage: 0.02
numNodesToRemove: 100 # per iteration
dpi: 500
initialLog: 1
logFreq: 8    # From x to x iterations we calculate graph stats
layout: 'spring'    # 'spring', 'spectral', 'shell'
