dataset: 'src/data/power.gml'
attackType: hubs  # random
stopCondition: density
stopCondArgs:
  threshold: 50e-5
hubPercentage: 0.02
numNodesToRemove: 2
initialLog: 10
logFreq: 5    # From x to x iterations we calculate graph stats
